### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by Razenbull** [scottrblock/ember-cli-scsslint#4]
First, thank you for your job !

I have an error that occurred after installation of ember-cli-scsslint. Can you, please, help me find the problem?

running

```
"ember-cli": "1.13.8"
```

Here is my _ember-cli-build.js_

``` javascript
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function (defaults) {
    var app = new EmberApp(defaults, {
        // Add options here

        'ember-cli-bootstrap-sassy': {
            'js': ['transition', 'collapse', 'dropdown', 'affix'],
            'glyphicons': false
        },

        'sassOptions': {
            'includePaths': [
                'bower_components/font-awesome/scss'
            ]
        }
    });

    // Use `app.import` to add additional libraries to the generated
    // output files.
    //
    // If you need to use different assets in different
    // environments, specify an object as the first parameter. That
    // object's keys should be the environment name and the values
    // should be the asset to use in that environment.
    //
    // If the library that you are including contains AMD or ES6
    // modules that you would like to import into your application
    // please specify an object with the list of modules as keys
    // along with the exports of each module as its value.

    return app.toTree();
};
```

and this is the error i get

```
Processing app.scss
File: app.scss
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at Object.SCSSLint.lint (/Users/adminuser/PhpstormProjects/hireme-frontend/node_modules/ember-cli-scsslint/node_modules/broccoli-scss-lint/lib/scss-lint.js:235:55)
    at SCSSLint.processString (/Users/adminuser/PhpstormProjects/hireme-frontend/node_modules/ember-cli-scsslint/node_modules/broccoli-scss-lint/index.js:48:22)
    at SCSSLint.processFile (/Users/adminuser/PhpstormProjects/hireme-frontend/node_modules/ember-cli-scsslint/node_modules/broccoli-scss-lint/index.js:104:31)
    at /Users/adminuser/PhpstormProjects/hireme-frontend/node_modules/ember-cli-scsslint/node_modules/broccoli-scss-lint/node_modules/broccoli-filter/index.js:85:21
    at lib$rsvp$$internal$$tryCatch (/Users/adminuser/PhpstormProjects/hireme-frontend/node_modules/ember-cli-scsslint/node_modules/broccoli-scss-lint/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/adminuser/PhpstormProjects/hireme-frontend/node_modules/ember-cli-scsslint/node_modules/broccoli-scss-lint/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/adminuser/PhpstormProjects/hireme-frontend/node_modules/ember-cli-scsslint/node_modules/broccoli-scss-lint/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/adminuser/PhpstormProjects/hireme-frontend/node_modules/ember-cli-scsslint/node_modules/broccoli-scss-lint/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by scottrblock** [comment]
Hm, I'm not exactly sure what's going on, but I think you need to replace `return app.toTree();` with  `module.exports = app.toTree();`. The latter but not the former worked for me locally.

**Comment by Razenbull** [comment]
Thank you for your help @scottrblock, I tested your solution but I get errors trying to build my app.
I'll investigate...
